# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftOCRTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftOCRTest
  pod 'SwiftOCR'

  target 'SwiftOCRTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftOCRTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
