# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebSeverDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebSeverDemo
  pod "GCDWebServer", "~> 3.0"
  pod "GCDWebServer/WebUploader", "~> 3.0"
  pod "GCDWebServer/WebDAV", "~> 3.0"

  target 'WebSeverDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WebSeverDemoUITests' do
    # Pods for testing
  end

end
