# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '3D 全景' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 3D 全景
pod "CTPanoramaView", "~> 1.3"

  target '3D 全景Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '3D 全景UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
